[Data]

# Name of the x column in the input data. Default: "x"
x-column = "global_x"

# Name of the y column in the input data. Default: "y"
y-column = "global_y"

# Name of the y column in the input data. Default: "z"
z-column = "global_z"

# Name of gene column in the input data. Default: "gene"
gene-column = "gene"

# Minimal number of molecules per gene. Default: 1
min-molecules-per-gene = 1

# Minimal number of molecules for a cell to be considered as real. It's an important parameter, as it's used to infer several other parameters. Default: 3
min-molecules-per-cell = 50

# Scale parameter, which suggest approximate cell radius for the algorithm. This parameter is required.
scale = 250

# Standard deviation of scale across cells. Can be either number, which means absolute value of the std, or string ended with "%" to set it relative to scale. Default: "25%"
scale-std = "25%"

# Use scale estimate from DAPI if provided. Default: true
estimate-scale-from-centers = true

# Minimal number of molecules in a segmented region, required for this region to be considered as a possible cell. Default: min-molecules-per-cell / 4
min-molecules-per-segment = 15

[Sampling] # These parameters shouldn't normally be changed

# Prior weight of assignment a molecule to new component. Default: 0.2
new-component-weight = 0.2

# Fraction of distributions, sampled at each stage. Default: 0.3
new-component-fraction = 0.3

[Plotting]

# Number of neighbors (i.e. 'k' in k-NN), which is used for gene composition visualization. Larger numbers leads to more global patterns. Default: estimate from min-molecules-per-cell
gene-composition-neigborhood = 20

# Number of pixels per cell of minimal size, used to estimate size of the final plot. For most protocols values around 7-30 give enough visualization quality. Default: 15
min-pixels-per-cell = 15
